version: "3.8"

networks:
  microservice-network:
    external: true

services:
  mongodb:
    image: mongo
    container_name: 'mongodb'
    networks:
      - microservice-network
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ~/db-data:/data/db  

  go-microservice:
    image: go-microservice
    container_name: 'go-microservice'
    depends_on:
      - mongodb
    networks:
      - microservice-network
    ports:
      - 50051:50051
  
  # mongo-ui:
  #   image: mongo-express
  #   networks:
  #     - microservice-network
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
  #     - ME_CONFIG_MONGODB_SERVER=mongodb